In [2]:
import numpy as np

# Input (Row Vector)
X = np.array([[1, 0, 1]])

# Target
Y = np.array([[1]])

np.random.seed(0)

W1 = np.random.rand(3,2)
b1 = np.random.rand(1,2)

W2 = np.random.rand(2,1)
b2 = np.random.rand(1,1)

learning_rate = 0.01

# Activation
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

# Forward
Z1 = np.dot(X, W1) + b1
A1 = sigmoid(Z1)

Z2 = np.dot(A1, W2) + b2
A2 = sigmoid(Z2)

# Mean Squared Error
loss = np.mean((Y - A2)**2)
print("Loss Before Training:", loss)

# Backpropagation (MSE)
dA2 = (A2 - Y) * sigmoid_derivative(A2)

dW2 = np.dot(A1.T, dA2)
db2 = dA2

dA1 = np.dot(dA2, W2.T)
dZ1 = dA1 * sigmoid_derivative(A1)

dW1 = np.dot(X.T, dZ1)
db1 = dZ1

# Update
W1 = W1 - learning_rate * dW1
b1 = b1 - learning_rate * db1

W2 = W2 - learning_rate * dW2
b2 = b2 - learning_rate * db2

print("Updated W1:")
print(W1)

print("Updated b1:")
print(b1)

print("Updated W2:")
print(W2)

print("Updated b2:")
print(b2)

Loss Before Training: 0.016541608539405547
Updated W1:
[[0.54883541 0.71519412]
 [0.60276338 0.54488318]
 [0.42367671 0.64589887]]
Updated b1:
[[0.43760912 0.89177776]]
Updated W2:
[[0.96377862]
 [0.38357195]]
Updated b2:
[[0.79186918]]
