In [2]:
import numpy as np

X = np.array([[1,0,1]])
Y = np.array([[1,0]])

W1 = np.array([[0.4,0.3],
               [0.2,0.5],
               [0.1,0.6]])

b1 = np.array([[0.2,0.3]])

W2 = np.array([[0.5,0.2],
               [0.7,0.4]])

b2 = np.array([[0.1,0.2]])

learning_rate = 0.1

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

# Forward
Z1 = np.dot(X, W1) + b1
A1 = sigmoid(Z1)

Z2 = np.dot(A1, W2) + b2
A2 = sigmoid(Z2)

loss = np.mean((Y - A2)**2)
print("Loss:", loss)

# Backpropagation
dA2 = (A2 - Y) * sigmoid_derivative(A2)

dW2 = np.dot(A1.T, dA2)
db2 = dA2

dA1 = np.dot(dA2, W2.T)
dZ1 = dA1 * sigmoid_derivative(A1)

dW1 = np.dot(X.T, dZ1)
db1 = dZ1

# Update
W1 = W1 - learning_rate * dW1
b1 = b1 - learning_rate * db1

W2 = W2 - learning_rate * dW2
b2 = b2 - learning_rate * db2

# Print Updated Values
print("Updated W1:")
print(W1)

print("Updated b1:")
print(b1)

print("Updated W2:")
print(W2)

print("Updated b2:")
print(b2)

Loss: 0.2521729314472602
Updated W1:
[[0.39994958 0.29962739]
 [0.2        0.5       ]
 [0.09994958 0.59962739]]
Updated b1:
[[0.19994958 0.29962739]]
Updated W2:
[[0.50365211 0.19010993]
 [0.70420052 0.3886248 ]]
Updated b2:
[[0.10546569 0.18519866]]
